### ISSUE TITLE
Getting errors while running wasm

### ISSUE THREAD

**Issue by tbitowt** [thomasfn/ScreepsDotNet#12]
After compiling example application and running it in Screeps:World I receive following errors in Screeps Console:

```
[22:48:54]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:48:54]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:48:54]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:48:54]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:48:54]DOTNET: at ScreepsDotNet.Program.Loop()
```

I done following steps:
1. Checked out `[ScreepsDotNet](https://github.com/thomasfn/ScreepsDotNet)`
2. Compiled wasm via `dotnet publish -c Debug`
3. Copied `bin\Debug\net8.0\wasi-wasm\AppBundle\world` content to my `AppData\Local\Screeps\scripts\screeps.com\dotnetTest` folder
4. Opened `dotnetTest` branch in Screeps:World
5. Went into `Console`, cleared and re-runned script

**Comment by tbitowt** [comment]
Full log here:

```
[22:56:57]DOTNET: Started WASI in 0 ms
[22:56:57]#1017: INIT SUCCESS (Infinityms remaining cpu this tick)
[22:56:58]DOTNET: Adding room manager for Room['sim'] as it is now visible and controlled by us
[22:56:58]DOTNET: RoomManager[sim]: Creep['sim_2067637059']([25,24:sim]) has unknown role!
[22:56:58]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:56:58]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:56:58]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:56:58]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:56:58]DOTNET: at ScreepsDotNet.Program.Loop()
[22:56:59]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:56:59]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:56:59]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:56:59]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:56:59]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:00]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:00]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:00]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:00]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:00]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:01]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:01]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:01]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:01]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:01]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:02]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:02]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:02]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:02]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:02]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:03]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:03]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:03]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:03]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:03]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:04]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:04]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:04]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:04]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:04]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:05]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:05]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:05]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:05]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:05]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:06]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:06]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:06]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:06]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:06]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:07]#1027: INIT state refreshed, beginning init sequence
[22:57:07]#1027: INIT loaded js dependencies (0ms)
[22:57:07]DOTNET: Compiled wasm module in 0 ms
[22:57:07]DOTNET: Instantiated wasm module in 0 ms
[22:57:08]DOTNET: Started WASI in 0 ms
[22:57:08]#1028: INIT SUCCESS (Infinityms remaining cpu this tick)
[22:57:09]DOTNET: Adding room manager for Room['sim'] as it is now visible and controlled by us
[22:57:09]DOTNET: RoomManager[sim]: Creep['sim_2067637059']([25,24:sim]) has unknown role!
[22:57:09]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:09]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:09]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:09]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:09]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:10]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:10]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:10]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:10]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:10]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:12]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:12]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:12]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:12]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:12]DOTNET: at ScreepsDotNet.Program.Loop()
[22:57:13]DOTNET: ScreepsDotNet.Interop.JSException: Error: failed to marshal null as 'JSObject'
[22:57:13]DOTNET: at ScreepsDotNet.Interop.Native.InvokeImport(Int32 , Span`1 )
[22:57:13]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.Native_GetHeapStatistics()
[22:57:13]DOTNET: at ScreepsDotNet.Native.World.NativeCpu.GetHeapStatistics()
[22:57:13]DOTNET: at ScreepsDotNet.Program.Loop()
```
